### ISSUE TITLE
minor bugs

### ISSUE THREAD

**Issue by jonathan-meyer** [cfjedimaster/SWAPI-Wrapper#7]
Two things:

1) URL needs to be "https"
2) need to remove the "User-Agent" header. 

![image](https://user-images.githubusercontent.com/20321382/55831611-82cb1700-5ae1-11e9-94d0-9c6541bc831f.png)

**Comment by jonathan-meyer** [comment]
you could also simplify the `request()` function with `fetch()`

```JS
  function request(url, cb) {
    fetch(url)
      .then(res => res.json())
      .then(cb)
      .catch(err => console.log(err));
  }
```

**Comment by cfjedimaster** [comment]
Makes sense - want to do a PR? When I wrote this years ago, Fetch wasn't as prevalent as it was now (afaik).

**Comment by jonathan-meyer** [comment]
Sure, I'll submit a PR. 
I figured as much with the fetch() call.

**Comment by jonathan-meyer** [comment]
see #8
